language: android
dist: trusty
group: edge
jdk: oraclejdk8
branches:
  only:
    - master
    - dev
env:
  - MAJOR_MINOR=1.1.0
android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.2
    - android-27
    - extra-google-m2repository
before_install:
  - if [ "$TRAVIS_BRANCH" == "master" ] ;then export TRAVIS_BUILD_NUMBER=1742 ;else export TRAVIS_BUILD_NUMBER=1743; fi
  - yes | sdkmanager "platforms;android-27"
  - git fetch --tags
script:
  - bash ./gradlew assembleDebug check;
  - bash ./gradlew app:assembleRelease check;
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.android/build-cache"
after_success:
  - cp app/build/outputs/apk/debug/app-debug.apk Lawnchair-$MAJOR_MINOR.$TRAVIS_BUILD_NUMBER.apk
  - cp app/build/outputs/mapping/debug/mapping.txt proguard-$MAJOR_MINOR.$TRAVIS_BUILD_NUMBER.txt
  - if [ "$TRAVIS_BRANCH" == "master" ] ;then mkdir -p bin ;else git clone https://github.com/Jerry981028/Lawnchair.git -b out bin/ ;fi
  - mv Lawnchair-$MAJOR_MINOR.$TRAVIS_BUILD_NUMBER.apk bin/
  - mv proguard-$MAJOR_MINOR.$TRAVIS_BUILD_NUMBER.txt bin/
  - cd bin
  - if [ "$TRAVIS_BRANCH" == "master" ] ;then git init ;fi
  - git config user.name "bot"
  - git config user.email "bot@github.com"
  - git add .
  - TAG="Lawnchair-${MAJOR_MINOR}.${TRAVIS_BUILD_NUMBER}"
  - git commit -m "$TAG"
  - git push --force --quiet "https://${GitHub_Token}@github.com/Jerry981028/Lawnchair.git" HEAD:out
